[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["cd frontend && npm ci", "cd backend && npm ci"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "node backend/index.js"

[variables]
NODE_TLS_REJECT_UNAUTHORIZED = "0"
