services:
  - type: web
    name: frescoop-api
    runtime: node
    region: frankfurt
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js --api-only
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: CORS_ORIGINS
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: TOKEN_SECRET
        sync: false
      - key: PAYDUNYA_MASTER_KEY
        sync: false
      - key: PAYDUNYA_PRIVATE_KEY
        sync: false
      - key: PAYDUNYA_TOKEN
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /api/health
